apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: peer0.bcosorg1.bcos-test
  name: peer0.bcosorg1.bcos-test
  namespace: bcos-test
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: peer0.bcosorg1.bcos-test
    spec:
      containers:
      - name: peer0-bcosorg1
        image: fiscoorg/front:bsn-gm-1.2.3
        ports:
        - containerPort: 8545
        - containerPort: 20200
        - containerPort: 30300
        - containerPort: 5002
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: peer0-bcosorg1-conf
        - mountPath: /dist/conf/application.yml
          name: peer0-bcosorg1-appconf
        workingDir: /data
      restartPolicy: Always
      volumes:
      - name: peer0-bcosorg1-conf
        hostPath:
          path: /data/nodes/fisco-0/node0
      - name: peer0-bcosorg1-appconf
        hostPath:
          path: /data/nodes/fisco-0/nodes/application.yml
status: {}


---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: peer0.bcosorg1.bcos-test
  name: peer0-bcosorg1
  namespace: bcos-test
spec:
  clusterIP: none
  ports:
  - name: rpc
    port: 8545
    targetPort: 8545
  - name: channel
    port: 20200
    targetPort: 20200
  - name: p2p
    port: 30300
    targetPort: 30300
  - name: front
    port: 5002
    targetPort: 5002
  selector:
    io.kompose.service: peer0.bcosorg1.bcos-test