apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: peer0.org4
  name: peer0.org4
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: peer0.org4
    spec:
      containers:
      - name: peer0-org4
        image: fiscoorg/front:v0.8
        ports:
        - containerPort: 8545
        - containerPort: 20200
        - containerPort: 30300
        - containerPort: 5002
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: peer0-org4-conf
        - mountPath: /opt
          name: peer0-org4-data
        - mountPath: /dist/log
          name: peer0-org4-frontlog
        - mountPath: /dist/conf/application.yml
          name: peer0-org4-appconf
        workingDir: /data
      restartPolicy: Always
      volumes:
      - name: peer0-org4-conf
        hostPath:
          path: /data/nodes/172.17.0.4/node0
      - name: peer0-org4-frontlog
        hostPath:
          path: /data/nodes/172.17.0.4/frontlog
      - name: peer0-org4-appconf
        hostPath:
          path: /data/nodes/application.yml
status: {}
