apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: peer0.org3
  name: peer0-org3
spec:
  clusterIP: 172.18.255.21
  ports:
  - name: rpc
    port: 8545
    targetPort: 8545
  - name: channel
    port: 20200
    targetPort: 20200
  - name: p2p
    port: 30300
    targetPort: 30300
  - name: front
    port: 5002
    targetPort: 5002
  selector:
    io.kompose.service: peer0.org3