apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: peer1.bcosorg2.bcos-test
  name: peer1-bcosorg2
  namespace: bcos-test
spec:
  clusterIP: 172.18.255.23
  ports:
  - name: rpc
    port: 8545
    targetPort: 8545
  - name: channel
    port: 20200
    targetPort: 20200
  - name: p2p
    port: 30300
    targetPort: 30300
  - name: front
    port: 5002
    targetPort: 5002
  selector:
    io.kompose.service: peer1.bcosorg2.bcos-test