kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: peer1-bcosorg2-pvc-bcos-test
  namespace: bcos-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi